# Generated by Django 4.2.5 on 2023-10-16 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_user",
                    models.IntegerField(
                        choices=[(1, "Student"), (2, "Teacher"), (3, "Administrator")]
                    ),
                ),
                ("matiere_enseigne", models.CharField(max_length=100)),
                ("ni_etudiant", models.CharField(max_length=20)),
                ("niveau_etudiant", models.CharField(max_length=2)),
                ("parcours_etudiant", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(default=timezone.now)
                ),
                ("updated_at", models.DateTimeField(default=timezone.now)
                ),
            ],
        ),
    ]
